project:
  type: website
  render:
    - "*.qmd"
    - "!*.ipynb"
    - "!*.Rmd"

  output-dir: docs

quarto-required: ">=1.3.*"
  

website:
  title: "Code snippets"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - post.qmd
      #- publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



